TencentBlueKing/bk-itsm

.pre-commit-config.yaml

feature: update pre-commit configuration file

---

.pre-commit-config.yaml
config/__init__.py

feature: remove some test configs

feature: remove_test_data

---

blueking/component/open/apis/sops.py
itsm/gateway/urls.py
itsm/gateway/views.py
itsm/pipeline_plugins/components/collections/bk_sops.py

feature: 标准运维节点支持多执行方案

---

.pre-commit-config.yaml
itsm/service/views.py
itsm/workflow/views.py

feature: 服务保存增加流程合法性校验
docs: 修改pre-commit 配置

feature: 服务保存增加流程合法性校验

---

docs/itsm_bkapi/ee/itsm.yaml
docs/itsm_bkapi/ee/itsm_ieod.yaml
itsm/openapi/service/views.py
itsm/service/models.py
itsm/workflow/serializers/field.py

feature: 网关接口适配项目改造

---

frontend/pc/src/components/form/advancedSearch/NewAdvancedSearch.vue
frontend/pc/src/views/processManagement/processDesign/nodeConfigue/sopsNode.vue
frontend/pc/src/views/service/serviceList.vue
frontend/pc/src/views/ticket/allTicket/index.vue

1.删除错误判断，
2.交互异常tooltips问题
3.单据高亮设置问题

bugfix_sops_node_length_and_experience_problem

---

itsm/project/serializers.py

feature: 更改项目创建校验规则

---

itsm/service/serializers.py
itsm/service/views.py

feature: 项目提单列表加载速度优化

---

itsm/service/models.py
itsm/service/serializers.py

bugfix: 修复关联单新建服务目录加载不出来的问题

---

itsm/workflow/validators.py

feature: 项目内字段库取消全局名称唯一限制

---

itsm/role/validators.py

feature: 用户组增加项目下唯一限制

---

support-files/iam/initial_common_actions.json

feature: 权限中心 common actions 移除单据查看

feature: 权限中心 common actions 移除单据查看

---

scripts/workflows/bk_ci.sh
scripts/workflows/code_quality.sh

feature: github action 修改单测配置

---

itsm/role/views.py

bugfix: 修复用户组编辑404的问题

---

itsm/ticket/permissions.py

bugfix: 修复督办人非处理人时无法督办的问题

---

frontend/pc/src/components/common/layout/Navigation.vue
frontend/pc/src/store/modules/project.js
frontend/pc/src/views/manage/globalSetting.vue
frontend/pc/src/views/processManagement/notice/noticeConfigure.vue
frontend/pc/src/views/processManagement/processDesign/nodeConfigue/components/dealPerson.vue
frontend/pc/src/views/project/editProjectDialog.vue
frontend/pc/src/views/project/index.vue
frontend/pc/src/views/project/role.vue

普通用户新建项目后没有自动刷新
全局配置中没有删除知识库的开关
通知配置的权限设置
项目列表加载全部

bugfix:2.6.0体验问题

---

itsm/ticket/models/misc.py

feature: 单据返回创建人和时间

---

frontend/pc/src/views/ticket/details/currentSteps/CurrentStepItem.vue
frontend/pc/src/views/ticket/details/currentSteps/nodetask/sopsDevopsTask.vue

Featrue: 单据详情蓝盾节点可预览

---

frontend/pc/src/views/ticket/details/index.vue

1.修复单据详情当前步骤不是评论还能下滑请求数据
2.:修改评论最大页数为1时的还请求数据的错误

bugfix:修改评论最大页数为1时的还请求数据的错误

---

frontend/pc/src/constants/routerList.js
frontend/pc/src/views/ticket/details/comment/editor.vue

bugfix:修复判断评论类型切换的权限

---

itsm/service/models.py
itsm/service/views.py
itsm/ticket/views/ticket_remark.py

bugfix: 服务目录相关权限问题修复

---

frontend/pc/src/views/processManagement/apiConfigure/apiTable.vue
frontend/pc/src/views/processManagement/publicField/index.vue
frontend/pc/src/views/processManagement/publicTrigger/index.vue
frontend/pc/src/views/ticket/details/index.vue

1.修改权限参数传错
2.无权限公共api导入功能任能打开
2.修改单据评论初始化总页数

bugfix:修改权限参数传错

---

frontend/pc/src/views/project/list.vue
frontend/pc/src/views/ticket/details/TicketHeader.vue
frontend/pc/src/views/ticket/details/components/tableFields.vue
frontend/pc/src/views/ticket/details/leftTicketContent.vue

1.修改单据当前步骤只有一个tab还能点击
2.修改新建单据返回icon的跳转
3.删除调试语句
4.修改项目管理列表的搜索关键字

bugfix:修改单据当前步骤只有一个tab还能点击和新建单据返回icon的跳转

---

itsm/component/constants/ticket.py
itsm/component/constants/trigger.py
itsm/service/views.py
itsm/tests/ticket/test_ticket.py
itsm/ticket/models/ticket.py
itsm/ticket/serializers/ticket.py
itsm/ticket/validators/field.py
itsm/trigger/rules/actions.py

feature: 后台支持自定义正则表达式校验
fature: 支持全局触发器
feature: 服务改为默认根据更新时间降序排列
feature: 单据can operate 计算规则修改

feature: 后台支持自定义正则表达式校验

---

adapter/config/sites/open/ver_settings.py
itsm/service/views.py
requirements_open.txt

[bugfix: 弹窗问题修复，blueapps 版本升级](https://github.com/TencentBlueKing/bk-itsm/commit/31005a533524ecf1a80cb4763011e6cdc7b1ca1d)
[feature: 去除服务展示过滤相关的内容](https://github.com/TencentBlueKing/bk-itsm/commit/90d9d142056c45952778caa2d1512b325391773a)

bugfix: 弹窗问题修复，blueapps 版本升级

---

frontend/pc/src/views/ticket/details/BasicInformation.vue
frontend/pc/src/views/ticket/details/components/fieldsDone.vue
frontend/pc/src/views/ticket/details/components/tableFields.vue
frontend/pc/src/views/ticket/details/currentSteps/CurrentStepItem.vue
frontend/pc/src/views/ticket/details/rightTicketTabs/LogTab.vue

1.审批节点自动处理不显示异常分派
2.异常分派按钮布局
3.单据log高度计算
4.单据基础信息编辑icon布局

bugfix: 单据体验问题

---

frontend/pc/src/views/project/notice.vue
frontend/pc/src/views/service/editService/ServiceForm.vue

1. 部分表单字段没有渲染出来
2. 通知模板页面 新增模板的通知场景需要去掉SLA选项

bugfix: ITSM问题修复

---

frontend/weixin/builds/webpack.base.conf.js

debug: 移动页面白屏调试

---

frontend/pc/src/views/commonMix/field.js

fix: 修复字段隐藏条件判断失败的问题

---

frontend/pc/build/webpack.prod.conf.js
frontend/pc/login_success.html
frontend/pc/package.json
frontend/pc/src/utils/ajax.js

chore: 中心统一登录窗口替换 --bug=116978891

---

frontend/pc/build/webpack.prod.conf.js
frontend/pc/package.json
frontend/pc/src/utils/ajax.js

fix: 登录成功页路径错误问题修复 --ignore

---

frontend/pc/src/utils/ajax.js
itsm/ticket/validators/field.py

bugfix: 修复联合校验未处理节点字段的问题
fix: 登录成功页路径错误问题修复

bugfix: 修复联合校验未处理节点字段的问题

---

frontend/pc/src/router/index.js

fix: 判断路径是否包含iframe逻辑错误修复 --ignore

---

frontend/pc/src/App.vue
frontend/pc/src/router/index.js

fix: 使用iframe依赖包方法路径错误修复 --ignore

---

frontend/pc/src/components/common/layout/Navigation.vue

fix: 退出登录c_url添加处理 --ignore

---

frontend/pc/src/views/project/editProjectDialog.vue
frontend/pc/src/views/service/editService/ServiceFormStep.vue

refactor: 新建服务、项目弹窗中名称表单项增加空格trim后校验

---

frontend/pc/.eslintrc.js
frontend/pc/index-dev.html
frontend/pc/index.html
frontend/pc/src/main.js

refactor: tam功能下线

---

frontend/pc/index.html

fix: 修复全局配置favicon不生效的问题 --bug=127065715
